version: '3'

networks: 
  front:

services:
  proxy-lb:
    image: nginx:1.13-alpine
    volumes: 
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - front
    ports:
      - 80:80

  web1:
    image: web
    networks: 
      - front
  web2:
    image: web
    networks: 
      - front